### ISSUE TITLE
Ocra TODO

### ISSUE THREAD

**Issue by rlober** [ocra-recipes/ocra-recipes#16]
Things we need to work on in the near future.
- [ ] Fix segfault when tasks are disconnected from the controller. #15 
- [ ] When a task is activated or deactivated make it progressive.
- [ ] Make a `TaskManagerOptions` class which is used for all `TaskManager` constructors and delete all the overloaded versions.
- [ ] Make a tool for comparing a new set of `TaskManagerOptions` to the existing tasks. If it doesn't exist, then add it. If it does exist, then update the task parameters.
- [ ] Add and remove tasks from a `ControllerClient`

**Comment by ahoarau** [comment]
- [x] Add "level" option in xml parser, defaults to 0

**Comment by rlober** [comment]
Ok so I think we can make a lot of simplifications by restructuring how we deal with tasks:
- Since we now only use `one-level` tasks I think it should be moved up to the parent `task` class and all other derived classes deleted. 
- All task-related methods in `TaskManager` should be moved to the task class - yarp ports etc. 
- Rather than have a bunch of specialized `TaskManagers` we just need to follow the `builder` design pattern and construct `tasks` that way. 
- All task construction should be done by the `Controller` class because we need the controller and the model to build a task. 
- All `TaskManagerSet` methods should then be put in the `Controller` class. 
- In `computeOutput()` in `Controller` we can add a loop to progressively add/remove tasks.

**Comment by rlober** [comment]
Lots of refactor since this initial post so closing.
